apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api-deployment
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {
          "name": "hello-api-deployment",
          "labels": {
            "app": "hello-api"
          }
        },
        "spec": {
          "replicas": 3,
          "selector": {
            "matchLabels": {
              "app": "hello-api"
            }
          },
          "template": {
            "metadata": {
              "labels": {
                "app": "hello-api"
              }
            },
            "spec": {
              "containers": [
                {
                  "name": "hello-api",
                  "image": "musk21/challenge10:1.0.0",
                  "ports": [
                    {
                      "containerPort": 3000
                    }
                  ]
                }
              ]
            }
          }
        }
      }
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
        - name: hello-api-v2
          image: musk21/challenge10:1.0.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: test-volume
              mountPath: /data/files

      volumes:
        - name: test-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: hello-api-service
spec:
  type: NodePort
  selector:
    app: hello-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
